theme: jekyll-theme-minimal
logo: /image/brand.png
show_downloads: true
github:
  zip_url: https://github.com/Bmxertv/EasyBan/zipball/master
  tar_url: https://github.com/Bmxertv/EasyBan/tarball/master
